### ISSUE TITLE
MissingPluginException(No implementation found for method startMonitoring on channel beacons_plugin)

### ISSUE THREAD

**Issue by EdoTez** [umair13adil/simple_beacons_flutter#60]
Hi all, 
I tried to download the example, there are no build errors and everything seems to work but my Iphone doesn't detect anything, running in debug I see this problem: 

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method startMonitoring on channel beacons_plugin)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      BeaconsPlugin.startMonitoring (package:beacons_plugin/beacons_plugin.dart:25:28)
<asynchronous suspension>
#2      _MyAppState.initPlatformState (package:my_beacons_app/main.dart:93:7)
<asynchronous suspension>`

I've tried searching the web but I can't find a solution, many say it's a caching porblem but I've tried recreating the project from scratch, importing everything and doing a clean build, nothing. 
Thank you very much for your help. 

Working environment: 
- MacBook Pro (15-inch, 2019) MacOS 12.1
- iPhone 13 Pro iOS 15.3.1
- Flutter 2.11.0-0.0.pre.493
- Dart 2.17.0 (build 2.17.0-87.0.dev) 
- DevTools 2.10.0

**Comment by EdoTez** [comment]
https://stackoverflow.com/questions/64130192/flutter-beacons-plugin-unhandled-exception-missingpluginexceptionno-implemen
